export const FETCH_ALL = 'FETCH_ALL_PROFESSIONALS';
export const CREATE = 'CREATE_PROFESSIONAL';
export const UPDATE = 'UPDATE_PROFESSIONAL';
export const FETCH = 'FETCH_PROFESSIONAL';
export const DELETE = 'DELETE_PROFESSIONAL';